/**
  ****************************(C) COPYRIGHT 2024 Polarbear****************************
  * @file       leg_model.c/h
  * @brief      轮腿的腿部模型（本部分函数大部分由matlab导出，基本不具备可读性）
  * @note
  * @history
  *  Version    Date            Author          Modification
  *  V1.0.0     Apr-7-2024      Penguin         1. done
  *
  @verbatim
  ==============================================================================

  ==============================================================================
  @endverbatim
  ****************************(C) COPYRIGHT 2024 Polarbear****************************
  */
#include "leg_model.h"

#include <math.h>

/**
 * @brief      腿部五连杆正运动学解算
 * @param[in]  phi1 后关节角度
 * @param[in]  phi4 前关节角度
 * @param[out] leg_pos 关节姿态 0-长度，1-角度
 */
void LegFKine(double phi1, double phi4, double leg_pos[2])
{
    double a;
    double b_a;
    double t14;
    double t15;
    double t2;
    double t3;
    double t4;
    double t5;
    double t6;
    double t8;
    /*     This function was generated by the Symbolic Math Toolbox version 9.3.
     */
    /*     2024-04-08 10:49:26 */
    t2 = cos(phi1);
    t3 = cos(phi4);
    t4 = sin(phi1);
    t5 = sin(phi4);
    t6 = t2 * 0.13;
    t8 = t4 * 0.13;
    t14 = t4 * 0.0624;
    t15 = t5 * 0.0624;
    t5 = t8 - t5 * 0.13;
    a = t14 - t15;
    b_a = (t3 * 0.13 - t6) + 0.15;
    t4 = (t3 * 0.0624 - t2 * 0.0624) + 0.072;
    t5 = t5 * t5 + b_a * b_a;
    t4 = atan(1.0 / (t4 + t5) *
              ((t15 - t14) + sqrt((a * a + t4 * t4) - t5 * t5))) *
         2.0;
    t5 = t8 + sin(t4) * 0.24;
    t4 = (t6 + cos(t4) * 0.24) - 0.075;
    leg_pos[0] = sqrt(t5 * t5 + t4 * t4);
    leg_pos[1] = atan2(t5, t4);
}
/**
 * @brief 腿部五连杆逆运动学解算
 */
void LegIKine(double l0, double phi0, double joint_pos[2])
{
    double t3;
    double t4;
    double t8;
    double t8_tmp;
    double t9;
    /*     This function was generated by the Symbolic Math Toolbox version 9.3.
     */
    /*     2024-04-08 10:49:26 */
    t3 = l0 * l0;
    t4 = l0 * cos(phi0) * 0.15;
    t8_tmp = t3 + t4;
    t8 = 1.0 / sqrt(t8_tmp + 0.005625);
    t9 = 1.0 / sqrt((t3 - t4) + 0.005625);
    joint_pos[0] = acos(t8 * (t4 + 0.01125) * 6.666666666666667) +
                   acos(t8 * (t8_tmp - 0.035075) * 3.8461538461538463);
    joint_pos[1] =
        (acos(t9 * (t4 - 0.01125) * 6.666666666666667) - 3.1415926535897931) +
        acos(t9 * ((-t3 + t4) + 0.035075) * 3.8461538461538463);
}
/**
 * @brief 获取腿部速度
 */
void LegSpeed(double dphi1, double dphi4, double phi1, double phi4, double speed[2])
{
    double t10_tmp;
    double t12_tmp;
    double t15;
    double t16;
    double t18;
    double t19;
    double t2;
    double t28;
    double t3;
    double t30;
    double t32;
    double t36;
    double t4;
    double t44;
    double t47;
    double t48;
    double t5;
    double t52;
    double t53;
    double t59;
    double t60;
    double t70;
    double t71;
    double t76;
    /*     This function was generated by the Symbolic Math Toolbox version 9.3.
     */
    /*     2024-04-08 10:49:26 */
    t2 = cos(phi1);
    t3 = cos(phi4);
    t4 = sin(phi1);
    t5 = sin(phi4);
    t10_tmp = t2 * 0.13;
    t12_tmp = t4 * 0.13;
    t15 = t2 * 0.0624;
    t16 = t3 * 0.0624;
    t18 = t4 * 0.0624;
    t19 = t5 * 0.0624;
    t28 = t12_tmp - t5 * 0.13;
    t30 = t18 - t19;
    t32 = (t3 * 0.13 - t10_tmp) + 0.15;
    t36 = (t16 - t15) + 0.072;
    t44 = t28 * t28 + t32 * t32;
    t47 = t2 * t28 * 0.26 + t4 * t32 * 0.26;
    t48 = t3 * t28 * 0.26 + t5 * t32 * 0.26;
    t52 = 1.0 / (t36 + t44);
    t53 = t52 * t52;
    t59 = sqrt((t30 * t30 + t36 * t36) - t44 * t44);
    t60 = 1.0 / t59;
    t32 = (t19 - t18) + t59;
    t28 = atan(t52 * t32) * 2.0;
    t70 = cos(t28);
    t71 = sin(t28);
    t76 = 1.0 / (t53 * (t32 * t32) + 1.0);
    t47 =
        (t18 + t47) * t53 * t32 +
        t52 * (t15 -
               t60 * ((t2 * t30 * 0.1248 + t4 * t36 * 0.1248) - t44 * t47 * 2.0) /
                   2.0);
    t28 =
        (t19 + t48) * t53 * t32 +
        t52 * (t16 -
               t60 * ((t3 * t30 * 0.1248 + t5 * t36 * 0.1248) - t44 * t48 * 2.0) /
                   2.0);
    t4 = t12_tmp + t71 * 0.24;
    t15 = (t10_tmp + t70 * 0.24) - 0.075;
    t59 = t70 * t76;
    t18 = t59 * t28;
    t53 = t71 * t76;
    t2 = t53 * t28;
    t28 = (-t10_tmp - t70 * 0.24) + 0.075;
    t60 = t28 * t28;
    t52 = 1.0 / t28;
    t32 = t4 * t4;
    t28 = 1.0 / sqrt(t32 + t15 * t15);
    t48 = 1.0 / (t32 + t60);
    t59 = t10_tmp - t59 * t47 * 0.48;
    t32 = t12_tmp - t53 * t47 * 0.48;
    speed[0] = dphi4 * t28 * (t4 * t18 * 0.96 - t15 * t2 * 0.96) / 2.0 +
               dphi1 * t28 * (t4 * t59 * 2.0 - t15 * t32 * 2.0) / 2.0;
    t28 = t4 * (1.0 / t60);
    speed[1] =
        dphi4 * t60 * t48 * (t52 * (0.0 - t18 * 0.48) + t28 * (t2 * 0.48)) -
        dphi1 * t60 * t48 * (t52 * t59 - t28 * t32);
}
/**
 * @brief 腿部五连杆VMC解算获取关节电机力矩
 */
void LegTransform(double F, double Tp, double phi1, double phi4, double T[2])
{
    double t100;
    double t102_tmp;
    double t108_tmp;
    double t120_tmp;
    double t123_tmp;
    double t124_tmp;
    double t131_tmp;
    double t16_tmp;
    double t174;
    double t175;
    double t18_tmp;
    double t21_tmp;
    double t22_tmp;
    double t24_tmp;
    double t25_tmp;
    double t50_tmp;
    double t54_tmp;
    double t59_tmp;
    double t5_tmp;
    double t77_tmp;
    double t7_tmp;
    double t81_tmp;
    double t82_tmp;
    double t91_tmp;
    /*     This function was generated by the Symbolic Math Toolbox version 9.3.
     */
    /*     2024-04-08 10:49:27 */
    t174 = cos(phi1);
    t5_tmp = cos(phi4);
    t175 = sin(phi1);
    t7_tmp = sin(phi4);
    t16_tmp = t174 * 0.13;
    t18_tmp = t175 * 0.13;
    t21_tmp = t174 * 0.0624;
    t22_tmp = t5_tmp * 0.0624;
    t24_tmp = t175 * 0.0624;
    t25_tmp = t7_tmp * 0.0624;
    t100 = t18_tmp - t7_tmp * 0.13;
    t50_tmp = t24_tmp - t25_tmp;
    t54_tmp = (t5_tmp * 0.13 - t16_tmp) + 0.15;
    t59_tmp = (t22_tmp - t21_tmp) + 0.072;
    t77_tmp = t100 * t100 + t54_tmp * t54_tmp;
    t81_tmp = t174 * t100 * 0.26 + t175 * t54_tmp * 0.26;
    t82_tmp = t5_tmp * t100 * 0.26 + t7_tmp * t54_tmp * 0.26;
    t54_tmp = 1.0 / (t59_tmp + t77_tmp);
    t91_tmp = t54_tmp * t54_tmp;
    t100 = sqrt((t50_tmp * t50_tmp + t59_tmp * t59_tmp) - t77_tmp * t77_tmp);
    t102_tmp = 1.0 / t100;
    t108_tmp = (t25_tmp - t24_tmp) + t100;
    t120_tmp = atan(t54_tmp * t108_tmp) * 2.0;
    t123_tmp = cos(t120_tmp);
    t124_tmp = sin(t120_tmp);
    t131_tmp = 1.0 / (t91_tmp * (t108_tmp * t108_tmp) + 1.0);
    t120_tmp =
        (t24_tmp + t81_tmp) * t91_tmp * t108_tmp +
        t54_tmp *
            (t21_tmp - t102_tmp *
                           ((t174 * t50_tmp * 0.1248 + t175 * t59_tmp * 0.1248) -
                            t77_tmp * t81_tmp * 2.0) /
                           2.0);
    t21_tmp =
        (t25_tmp + t82_tmp) * t91_tmp * t108_tmp +
        t54_tmp * (t22_tmp -
                   t102_tmp *
                       ((t5_tmp * t50_tmp * 0.1248 + t7_tmp * t59_tmp * 0.1248) -
                        t77_tmp * t82_tmp * 2.0) /
                       2.0);
    t24_tmp = t18_tmp + t124_tmp * 0.24;
    t81_tmp = (t16_tmp + t123_tmp * 0.24) - 0.075;
    t100 = (-t16_tmp - t123_tmp * 0.24) + 0.075;
    t174 = t100 * t100;
    t175 = 1.0 / t100;
    t100 = t24_tmp * t24_tmp;
    t102_tmp = t123_tmp * t131_tmp;
    t91_tmp = t16_tmp - t102_tmp * t120_tmp * 0.48;
    t82_tmp = t124_tmp * t131_tmp;
    t120_tmp = t18_tmp - t82_tmp * t120_tmp * 0.48;
    t108_tmp = F * (1.0 / sqrt(t100 + t81_tmp * t81_tmp));
    t54_tmp = Tp * t174 * (1.0 / (t100 + t174));
    t100 = t24_tmp * (1.0 / t174);
    T[0] = t108_tmp * (t24_tmp * t91_tmp * 2.0 - t81_tmp * t120_tmp * 2.0) / 2.0 -
           t54_tmp * (t175 * t91_tmp - t100 * t120_tmp);
    T[1] = t108_tmp *
               (t102_tmp * t24_tmp * t21_tmp * 0.96 -
                t82_tmp * t81_tmp * t21_tmp * 0.96) /
               2.0 +
           t54_tmp * (t175 * (0.0 - t102_tmp * t21_tmp * 0.48) +
                      t100 * (t82_tmp * t21_tmp * 0.48));
}
/**
 * @brief 腿部前馈计算
 */
double LegFeedforward(double theta)
{
    /*     This function was generated by the Symbolic Math Toolbox version 9.3.
     */
    /*     2024-03-26 16:19:12 */
    return cos(theta) * 38.815056;
}
/**
 * @brief LQR反馈矩阵计算
 */
void L2K(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     2024-03-18 11:58:20 */
  t2 = L0 * L0;
  t3 = L0 * L0 * L0;
  K[0] = ((L0 * -471.26895290849069 + t2 * 655.82771179456677) -
          t3 * 588.3102597819942) -
         33.946942389013763;
  K[1] = ((L0 * 67.93355856622631 - t2 * 299.68896582918688) +
          t3 * 352.052850180012) +
         24.146302504485291;
  K[2] = ((L0 * -46.558110626768539 - t2 * 59.647562966390211) +
          t3 * 41.70979643117) -
         11.33548614145108;
  K[3] = ((L0 * -6.3405825085466407 + t2 * 15.672601321835741) -
          t3 * 14.161872016176581) +
         7.4540007322748174;
  K[4] = ((L0 * -25.943755021409551 + t2 * 60.27738396726874) -
          t3 * 53.6960171711332) -
         17.613872554801819;
  K[5] = ((L0 * -40.635458780584571 + t2 * 60.150208570349967) -
          t3 * 36.579993054252192) +
         14.169989391295781;
  K[6] = ((L0 * -10.9848327194688 - t2 * 24.559200883204142) +
          t3 * 47.839287745993943) -
         37.386515524085418;
  K[7] = ((L0 * -91.437185828499182 + t2 * 176.47795931259941) -
          t3 * 146.67425720587451) +
         27.167894593487269;
  K[8] = ((L0 * -128.50060351277159 + t2 * 190.21166081747671) -
          t3 * 115.67609484590849) +
         44.809440896934881;
  K[9] = ((L0 * 82.041356925319178 - t2 * 190.61382473419741) +
          t3 * 169.80171554192819) +
         55.69995568908702;
  K[10] = ((L0 * -30.910579695490629 + t2 * 62.987841473601947) -
           t3 * 55.628594826648992) +
          9.3895495473674959;
  K[11] = ((L0 * 17.668378988995538 - t2 * 43.043680966815828) +
           t3 * 40.559039858925047) +
          3.506432700187557;
}
